### ISSUE TITLE
How to know what reason caused the imageproxy server down?

### ISSUE THREAD

**Issue by JaosnHsieh** [willnorris/imageproxy#103] opened 2017-08-10 11:08 UTC
I'm using`imageproxy --addr myip.1.1.1:8080 -cache /tmp/imageproxy`
to start my imageproxy server on Ubuntu 16.04 and try to test its limit and performance.

The server has only 300MB available memory. And I request images sequently image  by 
`xargs -n 1 curl -O < urls.txt` The urls.txt file has 300 more images urls.

After about 20 images I downloaded successfully to my Mac, the imageproxy server shut down with no error.
I've checked the following logs: 

1.  /tmp/imageproxy.ERROR
2. /tmp/imageproxy.INFO
3. /tmp/imageproxy.WARNING

Above logs only shows `image: unknown format`and some other has nothing to do with the reason shutting down the server.

And I also check the running console log, it shows some Go lang info:
```
goroutine 14 [IO wait]:
net.runtime_pollWait(0x7f00847c4e60, 0x72, 0x7)
	/usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42001ad88, 0x72, 0x8db480, 0x8d75e8)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42001ad88, 0xc42013d000, 0x1000)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42001ad20, 0xc42013d000, 0x1000, 0x1000, 0x0, 0x8db480, 0x8d75e8)
	/usr/lib/go-1.8/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e158, 0xc42013d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/net.go:181 +0x70
net/http.(*persistConn).Read(0xc420073200, 0xc42013d000, 0x1000, 0x1000, 0x4, 0x450310, 0xc420057500)
	/usr/lib/go-1.8/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc420057380)
	/usr/lib/go-1.8/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc420057380, 0x1, 0xc42003bbe5, 0x1, 0x0, 0xc420057620, 0x0)
	/usr/lib/go-1.8/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc420073200)
	/usr/lib/go-1.8/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.8/src/net/http/transport.go:1117 +0xa35

goroutine 15 [select]:
net/http.(*persistConn).writeLoop(0xc420073200)
	/usr/lib/go-1.8/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.8/src/net/http/transport.go:1118 +0xa5a
``` 
I check memory and cpu usage by `top` then I found out a suspicious process called `kswapd0` always shows before the server crashed.
After search I think it's because running out of memory. But there is no Error log for this.
Can this ERROR be logged in the log files? Or is there any way I can make sure the reasons it crashed?

**Comment by chocolatkey** [comment] 2017-11-07 06:34
k**swap**d0 => not a suspicious process. That mean the computer's swap space (disk RAM) is being used (probably intensely in your case).

**Comment by ramiel** [comment] 2018-02-02 10:28
I have the same error but I'm not using any cache

```
goroutine 1364 [IO wait]:
internal/poll.runtime_pollWait(0x7f750aeb6388, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4f5434b98, 0x72, 0xffffffffffffff00, 0x1060a60, 0x105b410)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4f5434b98, 0xc433968c00, 0x1, 0x1)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4f5434b80, 0xc433968c11, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc4f5434b80, 0xc433968c11, 0x1, 0x1, 0xba4, 0x3f948ff87a89d04c, 0xba5)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42d463a70, 0xc433968c11, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
net/http.(*connReader).backgroundRead(0xc433968c00)
        /usr/local/go/src/net/http/server.go:660 +0x62
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:656 +0xd8

goroutine 1972 [select]:
net/http.(*persistConn).writeLoop(0xc422927e60)
        /usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1187 +0xa53

```

What can it be?

**Comment by willnorris** [comment] 2019-03-27 22:53
can folks confirm whether they are still seeing this issue?  I'm finally getting around to trying to go through the issue backlog, and want to confirm whether this still happens.  Thanks.

**Comment by ramiel** [comment] 2019-03-28 07:48
I wrote my own image proxy meanwhile https://ramiel.gitlab.io/caravaggio/ :)

**Comment by JaosnHsieh** [comment] 2019-03-28 15:01
> can folks confirm whether they are still seeing this issue? I'm finally getting around to trying to go through the issue backlog, and want to confirm whether this still happens. Thanks.

I have no longer this server so I cannot reproduce it for now. thanks your work anyway.

**Comment by willnorris** [comment] 2019-03-28 15:16
cool, thanks for following up.  And that looks like a really cool project, @ramiel!

Closing as "not reproducible" for now.  If anyone sees this behavior again, feel free to reply here or open a new issue.

**Closed by willnorris** 2019-03-28 15:16 UTC
