### ISSUE TITLE
Cache issue.

### ISSUE THREAD

**Issue by teodor-pripoae** [willnorris/imageproxy#21] opened 2015-03-23 23:31 UTC
Hi,

I'm currently running imageproxy on a box with single core CPU and 768mb RAM. It is the only process aside nginx, both ran as docker containers.

After a few hours on a medium load (I don't have monitoring yet, but I can say about several hundred RPM) the server starts to return 500. The only way to make it work again is to restart the docker container.

The log looks like this:
```
2015/03/23 23:02:12 http: panic serving 172.17.42.1:42247: 7112 bytes still won't fit in the cache! (max 104857600 bytes)
goroutine 1583 [running]:
net/http.func·011()
	/usr/src/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x662420, 0xc20836da70)
	/usr/src/go/src/pkg/runtime/panic.c:248 +0x18d
io/ioutil.func·002()
	/usr/src/go/src/pkg/io/ioutil/ioutil.go:30 +0xf8
runtime.panic(0x662420, 0xc20836da70)
	/usr/src/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/peterbourgon/diskv.(*Diskv).ensureCacheSpaceFor(0xc208054280, 0x1bc8, 0x0, 0x0)
	/go/src/github.com/peterbourgon/diskv/diskv.go:471 +0x366
github.com/peterbourgon/diskv.(*Diskv).cacheWithLock(0xc208054280, 0xc208389260, 0x20, 0xc208a1a000, 0x1bc8, 0x3dc8, 0x0, 0x0)
	/go/src/github.com/peterbourgon/diskv/diskv.go:390 +0x61
github.com/peterbourgon/diskv.(*Diskv).cacheWithoutLock(0xc208054280, 0xc208389260, 0x20, 0xc208a1a000, 0x1bc8, 0x3dc8, 0x0, 0x0)
	/go/src/github.com/peterbourgon/diskv/diskv.go:414 +0xba
github.com/peterbourgon/diskv.(*siphon).Read(0xc20836aff0, 0xc20d0c5bc8, 0x238, 0x238, 0xdc8, 0x0, 0x0)
	/go/src/github.com/peterbourgon/diskv/diskv.go:270 +0x20e
io/ioutil.(*nopCloser).Read(0xc20836da40, 0xc20d0c5bc8, 0x238, 0x238, 0xdc8, 0x0, 0x0)
	<autogenerated>:4 +0x7b
bytes.(*Buffer).ReadFrom(0xc20d377030, 0x7f9e8ee13ec0, 0xc20836da40, 0x1bc8, 0x0, 0x0)
	/usr/src/go/src/pkg/bytes/buffer.go:169 +0x20e
io/ioutil.readAll(0x7f9e8ee13ec0, 0xc20836da40, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/pkg/io/ioutil/ioutil.go:33 +0x1ae
io/ioutil.ReadAll(0x7f9e8ee13ec0, 0xc20836da40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/pkg/io/ioutil/ioutil.go:42 +0x6c
github.com/peterbourgon/diskv.(*Diskv).Read(0xc208054280, 0xc208389260, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/peterbourgon/diskv/diskv.go:174 +0x196
github.com/gregjones/httpcache/diskcache.(*Cache).Get(0xc20803a060, 0xc208389260, 0x20, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/gregjones/httpcache/diskcache/diskcache.go:22 +0x95
github.com/gregjones/httpcache.CachedResponse(0x7f9e8ee12998, 0xc20803a060, 0xc20cbde680, 0x0, 0x0, 0x0)
	/go/src/github.com/gregjones/httpcache/httpcache.go:48 +0x8e
github.com/gregjones/httpcache.(*Transport).RoundTrip(0xc208024ba0, 0xc20cbde680, 0xc9, 0x0, 0x0)
	/go/src/github.com/gregjones/httpcache/httpcache.go:140 +0x1a5
net/http.send(0xc20cbde4e0, 0x7f9e8ee12a30, 0xc208024ba0, 0xc20cbde5b0, 0x0, 0x0)
	/usr/src/go/src/pkg/net/http/client.go:195 +0x43d
net/http.(*Client).send(0xc208024b40, 0xc20cbde4e0, 0x6d, 0x0, 0x0)
	/usr/src/go/src/pkg/net/http/client.go:118 +0x15b
net/http.(*Client).doFollowingRedirects(0xc208024b40, 0xc20cbde4e0, 0x7c3ea8, 0x0, 0x0, 0x0)
	/usr/src/go/src/pkg/net/http/client.go:343 +0x97f
net/http.(*Client).Get(0xc208024b40, 0xc20d376bd0, 0x6d, 0x1, 0x0, 0x0)
	/usr/src/go/src/pkg/net/http/client.go:275 +0xaf
github.com/teodor-pripoae/imageproxy.(*Proxy).ServeHTTP(0xc20803e1c0, 0x7f9e8ee13cc0, 0xc2082fdf40, 0xc20cbde0d0)
	/go/src/github.com/teodor-pripoae/imageproxy/imageproxy.go:99 +0x733
net/http.serverHandler.ServeHTTP(0xc2080040c0, 0x7f9e8ee13cc0, 0xc2082fdf40, 0xc20cbde0d0)
	/usr/src/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208c92d80)
	/usr/src/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
	/usr/src/go/src/pkg/net/http/server.go:1721 +0x313
```

**Comment by willnorris** [comment] 2015-03-29 16:09
So it looks like the disk-based cache is filling up, and then having trouble freeing up space.  I tried very briefly to reproduce, but wasn't able... I'll have to dig into it more.

@peterbourgon, do you have any ideas by chance?

**Comment by peterbourgon** [comment] 2015-03-29 16:11
@willnorris looks like you're using an old version of diskv?

**Comment by willnorris** [comment] 2015-03-29 16:13
imageproxy doesn't pin to any particular version.  @teodor-pripoae, try running the following to update the version of diskv you're using:

```
go get -u github.com/peterbourgon/diskv
```

**Comment by willnorris** [comment] 2015-05-04 01:16
I'm going to go ahead and close this.  @teodor-pripoae, if you still have this problem with a recent version of the diskv library, please feel free to reopen.

**Closed by willnorris** 2015-05-04 01:16 UTC
