### ISSUE TITLE
TLS SNI not working?

### ISSUE THREAD

**Issue by Tragen** [willnorris/imageproxy#170] opened 2019-02-22 13:42 UTC
Mattermost 5.8.0 includes your imageproxy.
For me it's not working currently as it doesn't work with TLS SNI.
I have one IP with multiple domains.
If only the IP or no TLS SNI is used, you get the default Apache HTTPS connection with a self signed certificate.
The domain is only reachable via https.

The response I get is:  "x509: certificate signed by unknown authority"
Our normal domain is using a LetsEncrypt certificate.

Is this only happening to me?

**Comment by willnorris** [comment] 2019-02-22 18:37
I'm aware that mattermost is using imageproxy, but I don't really know too much about how they handle inbound requests.  

imageproxy itself doesn't handle TLS at all (unless the mattermost folks made some changes).  Instead, it expects to sit behind an HTTP server that terminates the TLS connection (in my case, nginx, but it could be any server).  So if you're seeing SNI issues, it is likely due to a configuration issue in whatever web server is sitting in front of imageproxy terminating those connections.  

Maybe check with the mattermost community to see if anyone there has thoughts on what the problem might be?

**Comment by Tragen** [comment] 2019-02-22 20:35
I think it was a misunderstanding.
The proxy doesn't get the image from the remote url when the remote server needs TLS SNI.

**Comment by willnorris** [comment] 2019-02-22 20:49
ah, yes... I misunderstood the problem.  Go's http client definitely supports SNI, which I also use on all of my personal domains that I use imageproxy with.  Do you have an example test case that reproduces the problem?

**Comment by Tragen** [comment] 2019-02-22 21:31
e.g. use this image:
https://img.fauser.ag/avatar/imageproxy_Gnome-stock_person_bot.svg
in the Browser, it's working. With the imageproxy not.

**Comment by Tragen** [comment] 2019-02-22 23:10
I don't know if the proxy doesn't work for SVGs at all. Would be bad.
Here are more examples that don't work.
https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg
https://img.fauser.ag/avatar/imageproxy_avatar_bot_128.png

**Comment by willnorris** [comment] 2019-03-24 21:34
I believe this is a problem with the SSL setup of img.fauser.ag.  I can indeed recreate the issue [on my own imageproxy instance](https://willnorris.com/api/imageproxy/siMKxlKSDDv80r7VW06j15ORvKX9K9FAwNTFmn6uNBJQ=/https://img.fauser.ag/avatar/imageproxy_Gnome-stock_person_bot.svg) with the same error:

    x509: certificate signed by unknown authority

But a similar error also occurs when simply using curl:

```
% curl https://img.fauser.ag/avatar/imageproxy_Gnome-stock_person_bot.svg            
                                    
curl: (60) SSL certificate problem: unable to get local issuer certificate                                               
More details here: https://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"                                                  
 of Certificate Authority (CA) public keys (CA certs). If the default                                                    
 bundle file isn't adequate, you can specify an alternate file                                                           
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in                                                    
 the bundle, the certificate verification probably failed due to a                                                       
 problem with the certificate (it might be expired, or the name might                                                    
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use                                                    
 the -k (or --insecure) option.
```
Upon further inspection with openssl, it looks like img.fauser.ag is not presenting the intermediate Let's Encrypt certificate:

```
% openssl s_client -connect img.fauser.ag:443 -servername img.fauser.ag

CONNECTED(00000003)
depth=0 CN = img.fauser.ag
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = img.fauser.ag
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=img.fauser.ag
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=DE/ST=Bavaria/L=Gilching/O=FAUSER AG/OU=IT/CN=FAUSER AG - Server CA/emailAddress=info@fauser.ag
   i:/C=DE/ST=Bavaria/L=Gilching/O=FAUSER AG/CN=FAUSER AG/emailAddress=info@fauser.ag
2 s:/C=DE/ST=Bavaria/L=Gilching/O=FAUSER AG/CN=FAUSER AG/emailAddress=info@fauser.ag
   i:/C=DE/ST=Bavaria/L=Gilching/O=FAUSER AG/CN=FAUSER AG/emailAddress=info@fauser.ag
---
```

The image works when you load it in your browser because all major browsers directly trust the Let's Encrypt CA.  But most operating system CA bundles don't directly trust the Let's Encrypt CA, and so need to see the intermediate certificate issued by Digital Signature Trust Co.  Alternately, you could try and update your ca-certificates on your operating system with one that includes the Let's Encrypt CA.

By comparison, [the wikipedia URL works fine on my instance](https://willnorris.com/api/imageproxy/s2wo-YvdD3piPXJD63xa1rXszAtC-fpQvvgWrEohUDPc/https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg) because it has a valid SSL setup.  The error you were seeing has nothing to do with it being an SVG.

(closing this out, since it's a server configuration issue, but happy to continue to discuss)

**Closed by willnorris** 2019-03-24 21:34 UTC

**Comment by Tragen** [comment] 2019-03-24 22:56
Thanks for your help. They fixed the setup and now it's working.
