### ISSUE TITLE
stream error: stream ID 19; INTERNAL_ERROR

### ISSUE THREAD

**Issue by NARKOZ** [willnorris/imageproxy#156] opened 2018-07-30 09:46 UTC
We randomly get these errors:

```
error fetching remote image: Get https://cdn.example.com/thumbs_l_s_c9ef0b06142099cc53df98dfb64188a4.jpg#0x0,sa9svKTpXLBDk0qCkIpmW8xS0ILm7cNmiJd_LSt4vo1U=: stream error: stream ID 19; INTERNAL_ERROR
```

Is it possible to retry fetching an image when the remote server responds with an error?

**Comment by willnorris** [comment] 2019-03-28 00:20
Judging by some other discussion I can find relating to this error (notably, https://github.com/googleapis/google-cloud-go/issues/987 and https://github.com/googleapis/google-cloud-go/issues/784) this seems to be an upstream http2 error that's being passed along.  It also seems totally reasonable to add some retry logic around this, so I'll look into doing that.

However, I'm also not entirely clear if this is coming from the remote image server, or perhaps from a caching backend that might be using http as well.  Could you confirm what caching backend you're using, if any?  (I'll add some better logging regardless to try and make these types of issues easier to debug in the future)

**Comment by NARKOZ** [comment] 2019-03-28 09:02
We don't use imageproxy anymore, but if I recall correctly images were cached to local disk.

**Comment by willnorris** [comment] 2019-03-28 15:20
okay, thanks for following up!  

Since this was the only instance I've heard of this happening, I'm closing as "not reproducible".  If anyone else sees this issue, please feel free to reply and reopen, so we can dig into it more.

**Closed by willnorris** 2019-03-28 15:20 UTC
