### ISSUE TITLE
WebP pass-through if bad encoding

### ISSUE THREAD

**Issue by johnpipi** [willnorris/imageproxy#132] opened 2018-01-09 15:15 UTC
I ran into a situation where the image is webp even though it is .jpg extension but it says error in log 

`error transforming image: webp: non-Alpha VP8X is not implemented`

It still loads the image fine in chrome but firefox, safari, and ios app won't load if it goes through the imageproxy.  If you load the url without imageproxy then it works fine it will render the image in safari.   Shouldn't the image just pass-through the code basically the unchanged if webp and error decoding it?  But seems something changes after going through the imageproxy... Any ideas?

This is the image in question:

`https://assets13.modaoperandi.com/images/products/643353/239580/large_innika-choo-plaid-two-tier-scalloped-skirt-top.jpg`

**Comment by willnorris** [comment] 2018-01-09 20:12
what are the transformation options you are using that results in that error?  What happens when you don't have any transformation options at all?

Proxying it with no transform options [works for me](https://willnorris.com/api/imageproxy/s-6aclAFCWXoInt_wnMeL-hUfvLpNW0FLwV4NM-hXqXU/https://assets13.modaoperandi.com/images/products/643353/239580/large_innika-choo-plaid-two-tier-scalloped-skirt-top.jpg), though it does convert it to JPG.  I'm not 100% sure if that conversion is working as intended.  I know we consider all webp images as potentially having transform options, but it seems that we should be able to detect inside the transform code that nothing is being requested, and therefore pass it through.  I'll have to take a closer look at that later.

**Comment by johnpipi** [comment] 2018-01-10 06:22
I was using these transformation options

`http://domain.com/400,q80,fit/https://assets13.modaoperandi.com/images/products/643353/239580/large_innika-choo-plaid-two-tier-scalloped-skirt-top.jpg`

**Comment by willnorris** [comment] 2018-01-10 15:34
hmm... even with those transformation options, it [still works fine for me](https://willnorris.com/api/imageproxy/400,q80,fit,s-6aclAFCWXoInt_wnMeL-hUfvLpNW0FLwV4NM-hXqXU/https://assets13.modaoperandi.com/images/products/643353/239580/large_innika-choo-plaid-two-tier-scalloped-skirt-top.jpg) (or at the very least, I don't see any errors being logged, and it works in Firefox on Android, which is the only non-Chrome browser I've got easily available right now).  Could you test that URL in the various browsers you're seeing issues with?

Also, what platform and what version of Go are you using?  I'm admittedly grasping at straws here, but am curious why you're seeing issues.  The webp package is written in pure Go, so in theory there shouldn't be any platform differences.  Also, could you send me a live URL that exhibits these issues on your imageproxy instance, assuming it's publicly accessible?  (Feel free to send to the email in my GitHub profile if you'd rather not post it publicly)

**Comment by jamesrwhite** [comment] 2019-03-05 11:38
In case this helps others I was able to work around this in our fork by setting the user agent on origin requests to a version of a browser that [doesn't support webp](https://developers.google.com/speed/webp/faq). The majority of sites stop serving it to you then. In our case we're using:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
```

A cleaner approach is probably setting the `Accept` header to content types it is known the imageproxy supports but I haven't tested that.

**Comment by willnorris** [comment] 2019-03-27 00:00
We now have support for:
 - setting custom user agent (3444fd9cb)
 - sending proper accept header in requests (6aca1e0)
 - detecting content-type when not set in response header (cf54b2c)

Between these, I think this now properly handles the proxied request for `https://assets13.modaoperandi.com/images/products/643353/239580/large_innika-choo-plaid-two-tier-scalloped-skirt-top.jpg` in all the various forms I could come up with.  I'll close this as fixed, but if you still see any problems related to this issue, please let me know.

**Closed by willnorris** 2019-03-27 00:00 UTC

**Comment by kamilliano** [comment] 2020-02-27 10:26
If it helps anyone I used `https://github.com/chai2010/webp` library to handle webp transformation:
```	
case "webp":
		// use webp library to encode
		quality := opt.Quality
		if quality == 0 || quality > 100 {
			quality = defaultQuality
		}
		m = transformImage(m, opt)
		err = webp.Encode(buf, m, &webp.Options{Quality: float32(quality)})
		if err != nil {
			return nil, err
		}
```
This still requires through testing though across different platforms/mobile devices.
