### ISSUE TITLE
Using tags for Docker image

### ISSUE THREAD

**Issue by iammichiel** [willnorris/imageproxy#116] opened 2017-10-10 08:12 UTC
Hello Will, 

Thanks a lot for your work on this project. We have been using it for over a year now with great success. Millions of images resized. I have one question though, would it be possible to use tags for your docker image synced with the project tags? 

For instance, the docker image only has a single tag : `latest`, while the project has many tags. 

Docker page : https://hub.docker.com/r/willnorris/imageproxy/tags/
Project tags : https://github.com/willnorris/imageproxy/releases

It would be easier to manage/deploy if those tags were consistent. 
Thanks!

**Comment by willnorris** [comment] 2017-10-12 18:01
Awesome, I'm glad to hear that the project is useful for you!  I'm closing this as a duplicate of #99, which is asking the exact same thing.  As I recently noted there, I tried setting up tags in the Docker Hub settings, but the most recent build failed.  I haven't had a chance to track down what went wrong, but when I figure it out, I'll update that issue.

**Closed by willnorris** 2017-10-12 18:01 UTC
