### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by tungpg** [willnorris/imageproxy#171] opened 2019-03-13 15:43 UTC
Thank you for your great work. I am new to golang. Could you please tell me how to start the server with https support? 

Thanks so much in advance!

**Comment by tungpg** [comment] 2019-03-13 15:44
I mean: 
`https://myserverdomain.com/{options}/{remote_url}`

**Comment by willnorris** [comment] 2019-03-17 14:56
imageproxy doesn't have any native support for serving over https.  The expectation is that you'd run it behind or part of a server that handles that.  See more in #71.  

(I'll close this as a duplicate of #71, and leave that one open to track the feature request)

**Closed by willnorris** 2019-03-17 14:56 UTC
